version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules 
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - GOOGLE_CLIENT_ID=test-google-client-id
      - GOOGLE_CLIENT_SECRET=test-google-client-secret
      - JWT_SECRET=super-secret
      - FRONTEND_URL=http://localhost:3000/api/
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - VITE_BACKEND_URL=http://localhost:5000/api/
    depends_on:
      - backend

volumes:
  mongo-data:
