version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mern_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mern-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mern_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo_data:
